language: ruby
rvm:
  - 2.1.0
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.yml.config config/database.yml
  - psql -c 'create database founden_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate spec
