defaults: &defaults
  app_name: Founden
  app_id: app.founden.com
  oauth2_providers:
    google:
      client_id: 852245675621.apps.googleusercontent.com
      secret_key: e3VcSapzZa_tbU3VnW1OxNrB
  default_email: Founden <no-reply@founden.com>
  contact_email: Founden <support@founden.com>
  image:
    sizes:
      thumb: 100x100#
      small: 300x300>
      medium: 600x600>

development:
  <<: *defaults

test:
  <<: *defaults
  oauth2_providers:
    google:
      client_id: DUMMY_CLIENT_ID
      secret_key: DUMMY_SECRET

production:
  <<: *defaults
